version: '3'
services:
  app:
    build: .
    env_file:
      - ../env.list
    volumes:
      - ../sql-data:/go/src/labTelegramBot/data
    working_dir: /go/src/labTelegramBot/
    stdin_open: true
    tty: true
    network_mode: host