version: '3'
services:
  app:
    build: .
    env_file:
      - ../env.list
    volumes:
      - ../sqlite-data:./data
    working_dir: /go/src/labTelegramBot/cmd/
    ports:
      - "9000:9000"
    stdin_open: true
    tty: true
    network_mode: host